site_name: Promieniowanie elektromagnetyczne w Krakowie

theme:
  name: material
  favicon: images/cell-tower.png
  icon:
    logo: material/radio-tower

nav:
  - Wstęp: 'index.md'
  - Wniosek o inf. publ. 2019: 'udip-1.md'
  - ile-nas-to-kosztuje.md

markdown_extensions:
  - attr_list
  - pymdownx.tilde

google_analytics: ['UA-167791373-1', 'github']
